// 自动生成：基础物品数据（来源：wiki「武器」「护甲」参考页），请勿手改，重新运行 scripts/extract-baseitems.mjs 生成
import type { BaseWeapon, BaseArmor } from "./baseitems";

export const BASE_WEAPONS: BaseWeapon[] = [
  { name: "木棒 Club", prof: 2, dice: "1d6", range: "—", traits: "—", category: "简易近战武器·单手", group: "硬头锤", price: 1 },
  { name: "匕首 Dagger", prof: 3, dice: "1d4", range: "5/10", traits: "轻投，副手", category: "简易近战武器·单手", group: "轻刃", price: 1 },
  { name: "标枪 Javelin", prof: 2, dice: "1d6", range: "10/20", traits: "重投", category: "简易近战武器·单手", group: "矛", price: 5 },
  { name: "硬头锤 Mace", prof: 2, dice: "1d8", range: "—", traits: "多用", category: "简易近战武器·单手", group: "硬头锤", price: 5 },
  { name: "镰刀 Sickle", prof: 2, dice: "1d6", range: "—", traits: "副手", category: "简易近战武器·单手", group: "轻刃", price: 2 },
  { name: "矛 Spear", prof: 2, dice: "1d8", range: "—", traits: "多用", category: "简易近战武器·单手", group: "矛", price: 5 },
  { name: "带刺铁手套 Spiked gauntlet", prof: 2, dice: "1d6", range: "—", traits: "副手", category: "简易近战武器·单手", group: "徒手", price: 5 },
  { name: "轻型硬头锤 Light mace", prof: 2, dice: "1d6", range: "—", traits: "副手", category: "简易近战武器·单手", group: "硬头锤", price: 3 },
  { name: "短矛 Short spear", prof: 2, dice: "1d6", range: "5/10", traits: "轻投，副手", category: "简易近战武器·单手", group: "矛", price: 2 },
  { name: "骨质拳套 Talid", prof: 2, dice: "1d6", range: "—", traits: "副手", category: "简易近战武器·单手", group: "徒手", price: 5 },
  { name: "寡妇之刀 Widow's knife", prof: 3, dice: "1d4", range: "5/10", traits: "轻投，副手", category: "简易近战武器·单手", group: "轻刃", price: 1 },
  { name: "腕刃 Wrist razors", prof: 3, dice: "1d4", range: "—", traits: "副手", category: "简易近战武器·单手", group: "轻刃", price: 1 },
  { name: "巨木棒 Greatclub", prof: 2, dice: "2d4", range: "—", traits: "—", category: "简易近战武器·双手", group: "硬头锤", price: 1 },
  { name: "钉头锤 Morningstar", prof: 2, dice: "1d10", range: "—", traits: "—", category: "简易近战武器·双手", group: "硬头锤", price: 10 },
  { name: "木棍 Quarterstaff", prof: 2, dice: "1d8", range: "—", traits: "—", category: "简易近战武器·双手", group: "杖", price: 5 },
  { name: "巨镰 Scythe", prof: 2, dice: "2d4", range: "—", traits: "—", category: "简易近战武器·双手", group: "重刃", price: 5 },
  { name: "战斧 Battleaxe", prof: 2, dice: "1d10", range: "—", traits: "多用", category: "军用近战武器·单手", group: "斧", price: 15 },
  { name: "连枷 Flail", prof: 2, dice: "1d10", range: "—", traits: "多用", category: "军用近战武器·单手", group: "连枷", price: 10 },
  { name: "手斧 Handaxe", prof: 2, dice: "1d6", range: "5/10", traits: "重投，副手", category: "军用近战武器·单手", group: "斧", price: 5 },
  { name: "长剑 Longsword", prof: 3, dice: "1d8", range: "—", traits: "多用", category: "军用近战武器·单手", group: "重刃", price: 15 },
  { name: "细剑 Rapier", prof: 3, dice: "1d8", range: "—", traits: "—", category: "军用近战武器·单手", group: "轻刃", price: 25 },
  { name: "弯刀 Scimitar", prof: 2, dice: "1d8", range: "—", traits: "高重击", category: "军用近战武器·单手", group: "重刃", price: 10 },
  { name: "短剑 Short sword", prof: 3, dice: "1d6", range: "—", traits: "副手", category: "军用近战武器·单手", group: "轻刃", price: 10 },
  { name: "飞锤 Throwing hammer", prof: 2, dice: "1d6", range: "5/10", traits: "重投，副手", category: "军用近战武器·单手", group: "锤", price: 5 },
  { name: "战锤 Warhammer", prof: 2, dice: "1d10", range: "—", traits: "多用", category: "军用近战武器·单手", group: "锤", price: 15 },
  { name: "战镐 War pick", prof: 2, dice: "1d8", range: "—", traits: "高重击，小型，多用", category: "军用近战武器·单手", group: "镐", price: 15 },
  { name: "阔剑 Broadsword", prof: 2, dice: "1d10", range: "—", traits: "多用", category: "军用近战武器·单手", group: "重刃", price: 20 },
  { name: "寇派斯弯刀 Khopesh", prof: 2, dice: "1d8", range: "—", traits: "凶残1，多用", category: "军用近战武器·单手", group: "斧，重刃", price: 20 },
  { name: "轻型战镐 Light war pick", prof: 2, dice: "1d6", range: "—", traits: "高重击，副手", category: "军用近战武器·单手", group: "镐", price: 10 },
  { name: "多头鞭 Scourge", prof: 2, dice: "1d8", range: "—", traits: "副手", category: "军用近战武器·单手", group: "连枷", price: 3 },
  { name: "三叉戟 Trident", prof: 2, dice: "1d8", range: "3/6", traits: "重投，多用", category: "军用近战武器·单手", group: "矛", price: 10 },
  { name: "骑枪 Lance", prof: 2, dice: "1d10", range: "—", traits: "骑乘，小型，多用", category: "军用近战武器·单手", group: "矛", price: 12 },
  { name: "爪钩 Alhulak", prof: 3, dice: "1d8", range: "—", traits: "多用", category: "军用近战武器·单手", group: "连枷", price: 20 },
  { name: "双面骨斧 Carrikal", prof: 2, dice: "1d8", range: "—", traits: "凶残2", category: "军用近战武器·单手", group: "斧", price: 15 },
  { name: "弯刃大刀 Falchion", prof: 3, dice: "2d4", range: "—", traits: "高重击", category: "军用近战武器·双手", group: "重刃", price: 25 },
  { name: "长柄刀 Glaive", prof: 2, dice: "2d4", range: "—", traits: "触及", category: "军用近战武器·双手", group: "重刃，长武器", price: 25 },
  { name: "巨斧 Greataxe", prof: 2, dice: "1d12", range: "—", traits: "高重击", category: "军用近战武器·双手", group: "斧", price: 30 },
  { name: "巨剑 Greatsword", prof: 3, dice: "1d10", range: "—", traits: "—", category: "军用近战武器·双手", group: "重刃", price: 30 },
  { name: "长戟 Halberd", prof: 2, dice: "1d10", range: "—", traits: "触及", category: "军用近战武器·双手", group: "斧，长武器", price: 25 },
  { name: "重型连枷 Heavy flail", prof: 2, dice: "2d6", range: "—", traits: "—", category: "军用近战武器·双手", group: "连枷", price: 25 },
  { name: "长矛 Longspear", prof: 2, dice: "1d10", range: "—", traits: "触及", category: "军用近战武器·双手", group: "长武器，矛", price: 10 },
  { name: "巨锤 Maul", prof: 2, dice: "2d6", range: "—", traits: "—", category: "军用近战武器·双手", group: "锤", price: 30 },
  { name: "重型战镐 Heavy war pick", prof: 2, dice: "1d12", range: "—", traits: "高重击，小型", category: "军用近战武器·双手", group: "镐", price: 20 },
  { name: "长枪 Pike", prof: 2, dice: "1d10", range: "—", traits: "触及，小型", category: "军用近战武器·双手", group: "长武器，矛", price: 15 },
  { name: "长骨戟 Trikal", prof: 2, dice: "1d10", range: "—", traits: "触及", category: "军用近战武器·双手", group: "斧，长武器", price: 25 },
  { name: "混用剑 Bastard sword", prof: 3, dice: "1d10", range: "—", traits: "多用", category: "优异近战武器·单手", group: "重刃", price: 30 },
  { name: "拳匕 Katar", prof: 3, dice: "1d6", range: "—", traits: "高重击，副手", category: "优异近战武器·单手", group: "轻刃", price: 3 },
  { name: "矮人重锤 Craghammer", prof: 2, dice: "1d10", range: "—", traits: "凶残2，多用", category: "优异近战武器·单手", group: "锤", price: 20 },
  { name: "反曲刀 Kukri", prof: 2, dice: "1d6", range: "—", traits: "凶残1，副手", category: "优异近战武器·单手", group: "轻刃", price: 10 },
  { name: "格挡匕首 Parrying dagger", prof: 2, dice: "1d4", range: "—", traits: "护身，副手", category: "优异近战武器·单手", group: "轻刃", price: 5 },
  { name: "尖刺盾牌 Spiked shield", prof: 2, dice: "1d6", range: "—", traits: "副手", category: "优异近战武器·单手", group: "轻刃", price: 10 },
  { name: "投矛 Tratnyr", prof: 2, dice: "1d8", range: "10/20", traits: "重投，多用", category: "优异近战武器·单手", group: "矛", price: 10 },
  { name: "三头连枷 Triple", prof: 3, dice: "1d10", range: "—", traits: "多用", category: "优异近战武器·单手", group: "连枷", price: 15 },
  { name: "战争斧 Waraxe", prof: 2, dice: "1d12", range: "—", traits: "多用", category: "优异近战武器·单手", group: "斧", price: 30 },
  { name: "锯齿镐 Serrated pick", prof: 2, dice: "1d10", range: "—", traits: "高重击", category: "优异近战武器·单手", group: "镐", price: 15 },
  { name: "长鞭 Whip", prof: 3, dice: "1d4", range: "—", traits: "触及", category: "优异近战武器·单手", group: "鞭", price: 10 },
  { name: "轮刃 Cutting wheel", prof: 2, dice: "1d6", range: "—", traits: "护身，副手", category: "优异近战武器·单手", group: "轻刃", price: 10 },
  { name: "卓尔长刀 Drow long knife", prof: 3, dice: "1d6", range: "5/10", traits: "重投，副手", category: "优异近战武器·单手", group: "重刃", price: 15 },
  { name: "塔兰塔弯刀 Talenta tangat", prof: 2, dice: "1d8", range: "—", traits: "高重击，小型，多用", category: "优异近战武器·单手", group: "重刃", price: 20 },
  { name: "护腕斧 Gauntlet axe", prof: 2, dice: "1d8", range: "—", traits: "护身，副手", category: "优异近战武器·单手", group: "斧", price: 25 },
  { name: "捕网 Net", prof: 2, dice: "1d6", range: "2/5", traits: "重投，副手", category: "优异近战武器·单手", group: "连枷", price: 20 },
  { name: "骨质拳刃 Puchik", prof: 3, dice: "1d6", range: "—", traits: "高重击，副手", category: "优异近战武器·单手", group: "轻刃", price: 3 },
  { name: "歌唱棍 Singing stick", prof: 3, dice: "1d6", range: "—", traits: "护身，副手", category: "优异近战武器·单手", group: "硬头锤", price: 40 },
  { name: "龟甲刃 Tortoise blade", prof: 2, dice: "1d6", range: "—", traits: "副手", category: "优异近战武器·单手", group: "轻刃", price: 10 },
  { name: "刺链 Spiked chain", prof: 3, dice: "2d4", range: "—", traits: "触及", category: "优异近战武器·双手", group: "连枷", price: 30 },
  { name: "处刑斧 Execution axe", prof: 2, dice: "1d12", range: "—", traits: "凶残2，高重击", category: "优异近战武器·双手", group: "斧", price: 30 },
  { name: "全长巨剑 Fullblade", prof: 3, dice: "1d12", range: "—", traits: "高重击", category: "优异近战武器·双手", group: "重刃", price: 30 },
  { name: "巨矛 Greatspear", prof: 3, dice: "1d10", range: "—", traits: "触及", category: "优异近战武器·双手", group: "长武器，矛", price: 25 },
  { name: "矮人巨锤 Mordenkrad", prof: 2, dice: "2d6", range: "—", traits: "凶残1", category: "优异近战武器·双手", group: "锤", price: 30 },
  { name: "塔兰塔长镰 Talenta sharrash", prof: 3, dice: "1d8", range: "—", traits: "高重击，小型", category: "优异近战武器·双手", group: "重刃，长武器", price: 30 },
  { name: "绞索 Garrote", prof: 3, dice: "1d4", range: "—", traits: "高重击，小型", category: "优异近战武器·双手", group: "绞索", price: 1 },
  { name: "矛斧 Gouge", prof: 2, dice: "2d6", range: "—", traits: "凶残1", category: "优异近战武器·双手", group: "斧，矛", price: 30 },
  { name: "钳杖 Zadatl", prof: 2, dice: "1d8", range: "—", traits: "高重击，触及", category: "优异近战武器·双手", group: "长武器，矛", price: 30 },
  { name: "双头斧 Double axe", prof: 2, dice: "1d10", range: "—", traits: "厚重，副手", category: "双头武器", group: "斧", price: 40 },
  { name: "双头连枷 Double flail", prof: 2, dice: "1d8", range: "—", traits: "护身，厚重，副手", category: "双头武器", group: "连枷", price: 30 },
  { name: "双头剑 Double sword", prof: 3, dice: "1d6", range: "—", traits: "护身，副手", category: "双头武器", group: "轻刃", price: 40 },
  { name: "矮人矛斧 Urgrosh", prof: 2, dice: "1d12", range: "—", traits: "护身，厚重，副手", category: "双头武器", group: "斧", price: 10 },
  { name: "双头弯刀 Double scimitar", prof: 2, dice: "1d6", range: "—", traits: "护身，高重击，厚重，副手", category: "双头武器", group: "重刃", price: 40 },
  { name: "双头砍刀 Zulaat", prof: 2, dice: "2d4", range: "—", traits: "护身，厚重，副手", category: "双头武器", group: "重刃", price: 30 },
  { name: "双头爪钩 Cahulaks", prof: 2, dice: "1d8", range: "3/6", traits: "重投，触及，副手", category: "双头武器", group: "连枷", price: 25 },
  { name: "龙爪 Dragon paw", prof: 2, dice: "1d8", range: "—", traits: "护身，厚重，副手", category: "双头武器", group: "重刃", price: 40 },
  { name: "双头尖矛 Gythka", prof: 2, dice: "1d8", range: "5/10", traits: "护身，重投，副手", category: "双头武器", group: "矛", price: 25 },
  { name: "双头月牙刃 Lotulis", prof: 2, dice: "1d10", range: "—", traits: "护身，厚重，副手", category: "双头武器", group: "重刃", price: 40 },
  { name: "锁镰 Kusari-gama", prof: 2, dice: "1d10", range: "—", traits: "护身，触及，副手", category: "双头武器", group: "连枷", price: 10 },
  { name: "手弩 Hand crossbow", prof: 2, dice: "1d6", range: "10/20", traits: "自由装填", category: "简易远程武器·单手", group: "弩", price: 25 },
  { name: "投石索 Sling", prof: 2, dice: "1d6", range: "10/20", traits: "自由装填", category: "简易远程武器·单手", group: "投石索", price: 1 },
  { name: "弹射带 Dejada", prof: 2, dice: "1d8", range: "10/20", traits: "自由装填", category: "简易远程武器·单手", group: "投石索", price: 10 },
  { name: "弩 Crossbow", prof: 2, dice: "1d8", range: "15/30", traits: "次要装填", category: "简易远程武器·双手", group: "弩", price: 25 },
  { name: "连发弩 Repeating crossbow", prof: 2, dice: "1d8", range: "10/20", traits: "自由装填*", category: "简易远程武器·双手", group: "弩", price: 35 },
  { name: "连发弩矢匣 Magazine", prof: 0, dice: "—", range: "—", traits: "—", category: "简易远程武器·弹药", group: "—", price: 1 },
  { name: "三刃镖 Chatkcha", prof: 2, dice: "1d6", range: "6/12", traits: "轻投", category: "军用远程武器·单手", group: "轻刃", price: 10 },
  { name: "长弓 Longbow", prof: 2, dice: "1d10", range: "20/40", traits: "自由装填", category: "军用远程武器·双手", group: "弓", price: 30 },
  { name: "短弓 Shortbow", prof: 2, dice: "1d8", range: "15/30", traits: "自由装填，小型", category: "军用远程武器·双手", group: "弓", price: 25 },
  { name: "手里剑（5） Shuriken (5)", prof: 3, dice: "1d4", range: "6/12", traits: "轻投", category: "优异远程武器·单手", group: "轻刃", price: 1 },
  { name: "塔兰塔回旋镖 Talenta boomerang", prof: 2, dice: "1d4", range: "10/20", traits: "轻投", category: "优异远程武器·单手", group: "轻刃", price: 5 },
  { name: "希恩德瑞克回旋镖 Xen'drik boomerang", prof: 2, dice: "1d6", range: "6/12", traits: "轻投", category: "优异远程武器·单手", group: "轻刃", price: 10 },
  { name: "流星索 Bola", prof: 3, dice: "1d4", range: "4/8", traits: "轻投", category: "优异远程武器·单手", group: "连枷", price: 5 },
  { name: "巨弓 Greatbow", prof: 2, dice: "1d12", range: "25/50", traits: "自由装填", category: "优异远程武器·双手", group: "弓", price: 30 },
  { name: "优异弩 Superior crossbow", prof: 3, dice: "1d10", range: "20/40", traits: "次要装填", category: "优异远程武器·双手", group: "弩", price: 30 },
  { name: "吹箭筒 Blowgun", prof: 3, dice: "1d4", range: "5/10", traits: "次要装填，小型", category: "优异远程武器·双手", group: "吹箭筒", price: 5 },
];

export const BASE_ARMORS: BaseArmor[] = [
  { name: "布甲 Cloth", ac: 0, category: "轻甲", masterwork: false, minEnhance: 0, check: 0, speed: 0, special: "—", price: 1 },
  { name: "吉斯布甲 Githweave", ac: 0, category: "轻甲", masterwork: true, minEnhance: 3, check: 0, speed: 0, special: "+1意志", price: 0 },
  { name: "念织布甲 Mindweave", ac: 0, category: "轻甲", masterwork: true, minEnhance: 4, check: 0, speed: 0, special: "+2意志", price: 0 },
  { name: "精织布甲 Feyweave", ac: 1, category: "轻甲", masterwork: true, minEnhance: 4, check: 0, speed: 0, special: "—", price: 0 },
  { name: "巨灵布甲 Efreetweave", ac: 1, category: "轻甲", masterwork: true, minEnhance: 5, check: 0, speed: 0, special: "+1意志", price: 0 },
  { name: "念纹布甲 Mindpatterned", ac: 1, category: "轻甲", masterwork: true, minEnhance: 6, check: 0, speed: 0, special: "+2意志", price: 0 },
  { name: "星织布甲 Starweave", ac: 2, category: "轻甲", masterwork: true, minEnhance: 6, check: 0, speed: 0, special: "—", price: 0 },
  { name: "皮甲 Leather", ac: 2, category: "轻甲", masterwork: false, minEnhance: 0, check: 0, speed: 0, special: "—", price: 25 },
  { name: "卓尔皮甲 Drowmesh", ac: 2, category: "轻甲", masterwork: true, minEnhance: 3, check: 0, speed: 0, special: "+1反射", price: 0 },
  { name: "蛇皮皮甲 Snakeskin", ac: 2, category: "轻甲", masterwork: true, minEnhance: 4, check: 0, speed: 0, special: "+2反射", price: 0 },
  { name: "精制皮甲 Feyleather", ac: 3, category: "轻甲", masterwork: true, minEnhance: 4, check: 0, speed: 0, special: "—", price: 0 },
  { name: "咒缚皮甲 Anathema", ac: 3, category: "轻甲", masterwork: true, minEnhance: 5, check: 0, speed: 0, special: "+1反射", price: 0 },
  { name: "剑翅皮甲 Swordwing", ac: 3, category: "轻甲", masterwork: true, minEnhance: 6, check: 0, speed: 0, special: "+2反射", price: 0 },
  { name: "星制皮甲 Starleather", ac: 4, category: "轻甲", masterwork: true, minEnhance: 6, check: 0, speed: 0, special: "—", price: 0 },
  { name: "革甲 Hide", ac: 3, category: "轻甲", masterwork: false, minEnhance: 0, check: -1, speed: 0, special: "—", price: 30 },
  { name: "大地革甲 Earthhide", ac: 3, category: "轻甲", masterwork: true, minEnhance: 3, check: -1, speed: 0, special: "+1强韧", price: 0 },
  { name: "精怪革甲 Feyhide", ac: 3, category: "轻甲", masterwork: true, minEnhance: 4, check: -1, speed: 0, special: "+2强韧", price: 0 },
  { name: "黑暗革甲 Darkhide", ac: 4, category: "轻甲", masterwork: true, minEnhance: 4, check: -1, speed: 0, special: "—", price: 0 },
  { name: "伏形革甲 Stalkerhide", ac: 4, category: "轻甲", masterwork: true, minEnhance: 5, check: -1, speed: 0, special: "+1强韧", price: 0 },
  { name: "虚空革甲 Voidhide", ac: 4, category: "轻甲", masterwork: true, minEnhance: 6, check: -1, speed: 0, special: "+2强韧", price: 0 },
  { name: "长者革甲 Elderhide", ac: 5, category: "轻甲", masterwork: true, minEnhance: 6, check: -1, speed: 0, special: "—", price: 0 },
  { name: "链甲 Chainmail", ac: 6, category: "重甲", masterwork: false, minEnhance: 0, check: -1, speed: -1, special: "—", price: 40 },
  { name: "精工链甲 Finemail", ac: 7, category: "重甲", masterwork: true, minEnhance: 2, check: -1, speed: -1, special: "—", price: 0 },
  { name: "交织链甲 Braidmail", ac: 8, category: "重甲", masterwork: true, minEnhance: 3, check: -1, speed: -1, special: "—", price: 0 },
  { name: "晶钢链甲 Crysteel", ac: 8, category: "重甲", masterwork: true, minEnhance: 4, check: -1, speed: -1, special: "+2意志", price: 0 },
  { name: "熔锻链甲 Forgemail", ac: 9, category: "重甲", masterwork: true, minEnhance: 4, check: -1, speed: -1, special: "—", price: 0 },
  { name: "密织链甲 Weavemail", ac: 10, category: "重甲", masterwork: true, minEnhance: 5, check: -1, speed: -1, special: "+1意志", price: 0 },
  { name: "深狱链甲 Pitmail", ac: 11, category: "重甲", masterwork: true, minEnhance: 6, check: -1, speed: -1, special: "+2意志", price: 0 },
  { name: "灵锻链甲 Spiritmail", ac: 12, category: "重甲", masterwork: true, minEnhance: 6, check: -1, speed: -1, special: "—", price: 0 },
  { name: "鳞甲 Scale", ac: 7, category: "重甲", masterwork: false, minEnhance: 0, check: 0, speed: -1, special: "—", price: 45 },
  { name: "龙兽鳞甲 Drakescale", ac: 8, category: "重甲", masterwork: true, minEnhance: 2, check: 0, speed: -1, special: "—", price: 0 },
  { name: "飞龙鳞甲 Wyvernscale", ac: 9, category: "重甲", masterwork: true, minEnhance: 3, check: 0, speed: -1, special: "—", price: 0 },
  { name: "风暴鳞甲 Stormscale", ac: 9, category: "重甲", masterwork: true, minEnhance: 4, check: 0, speed: -1, special: "+2强韧", price: 0 },
  { name: "古龙鳞甲 Wyrmscale", ac: 10, category: "重甲", masterwork: true, minEnhance: 4, check: 0, speed: -1, special: "—", price: 0 },
  { name: "纳迦鳞甲 Nagascale", ac: 11, category: "重甲", masterwork: true, minEnhance: 5, check: 0, speed: -1, special: "+1强韧", price: 0 },
  { name: "泰坦鳞甲 Titanscale", ac: 12, category: "重甲", masterwork: true, minEnhance: 6, check: 0, speed: -1, special: "+2强韧", price: 0 },
  { name: "长者鳞甲 Elderscale", ac: 13, category: "重甲", masterwork: true, minEnhance: 6, check: 0, speed: -1, special: "—", price: 0 },
  { name: "板甲 Plate", ac: 8, category: "重甲", masterwork: false, minEnhance: 0, check: -2, speed: -1, special: "—", price: 50 },
  { name: "霜火板甲 Rimefire plate", ac: 8, category: "重甲", masterwork: true, minEnhance: 2, check: -2, speed: -1, special: "1全抗力", price: 0 },
  { name: "叠层板甲 Layered plate", ac: 9, category: "重甲", masterwork: true, minEnhance: 2, check: -2, speed: -1, special: "—", price: 0 },
  { name: "吉斯板甲 Gith plate", ac: 10, category: "重甲", masterwork: true, minEnhance: 3, check: -2, speed: -1, special: "—", price: 0 },
  { name: "幽灵板甲 Specter plate", ac: 10, category: "重甲", masterwork: true, minEnhance: 4, check: -2, speed: -1, special: "2全抗力", price: 0 },
  { name: "战争板甲 Warplate", ac: 11, category: "重甲", masterwork: true, minEnhance: 4, check: -2, speed: -1, special: "—", price: 0 },
  { name: "军团板甲 Legion plate", ac: 12, category: "重甲", masterwork: true, minEnhance: 5, check: -2, speed: -1, special: "—", price: 0 },
  { name: "末日板甲 Tarrasque plate", ac: 12, category: "重甲", masterwork: true, minEnhance: 6, check: -2, speed: -1, special: "5全抗力", price: 0 },
  { name: "神铸板甲 Godplate", ac: 14, category: "重甲", masterwork: true, minEnhance: 6, check: -2, speed: -1, special: "—", price: 0 },
  { name: "镶嵌皮甲 Studded Leather", ac: 3, category: "轻甲", masterwork: false, minEnhance: 0, check: 0, speed: 0, special: "坚固", price: 35 },
  { name: "环甲 Ring Mail", ac: 3, category: "轻甲", masterwork: false, minEnhance: 0, check: -1, speed: 0, special: "耐久2", price: 40 },
  { name: "镶钢链甲 Banded Mail", ac: 6, category: "重甲", masterwork: false, minEnhance: 0, check: -1, speed: -1, special: "坚固", price: 55 },
  { name: "板条甲 Splint Mail", ac: 7, category: "重甲", masterwork: false, minEnhance: 0, check: -2, speed: -1, special: "耐久3", price: 50 },
  { name: "钉板甲 Spiked Plate", ac: 8, category: "重甲", masterwork: false, minEnhance: 0, check: -3, speed: -1, special: "带刺", price: 55 },
  { name: "全身板甲 Full Plate", ac: 8, category: "重甲", masterwork: false, minEnhance: 0, check: -1, speed: -1, special: "坚固", price: 65 },
];

// 武器特性完整定义（来源：wiki「武器」页）
export const PROPERTY_DEFS: Record<string, string> = {
  "凶残": "一件凶残武器造成的最小伤害比普通武器高。在掷武器伤害时，重掷所有结果与武器的凶残值相等或更低的伤害骰。反复重掷这些伤害骰直到出现高于武器凶残值的数值，然后使用此新数值",
  "护身": "当你一手持用护身武器，另一手持用另一件近战武器时，护身武器给予你在AC上的+1加值。持用超过1件的护身武器不会增加此加值。要获得此增益，你不需要使用护身武器攻击，但是你必须擅长它",
  "重投": "投掷武器是从手中投射出去的远程武器，而不是用来发射投射物。以重投武器进行的远程基本攻击使用持用者的力量调整值来计算攻击骰和伤害骰，除非使用的威能描述中另有注明。",
  "高重击": "高重击武器在持用者以它造成重击时会造成更多伤害。若重击，在1-10级时造成1[W]额外伤害，在11-20级时造成2[W]额外伤害，在21-30级时造成3[W]额外伤害。若该武器是魔法武器，则此额外伤害是附加在该武器的任何重击伤害之外的",
  "轻投": "投掷武器是从手中投射出去的远程武器，而不是用来发射投射物。以轻投武器进行的远程基本攻击使用持用者的敏捷调整值来计算攻击骰和伤害骰，除非使用的威能描述中另有注明。",
  "装填": "发射投射物的远程武器，包括弓，弩，投石索，需要时间来装填。任何具有装填特性的武器都必须用双手装填，哪怕它只需要单手就能使用它攻击（例如，投石索是一种单手武器，但你需要空出另一只手来装填）。 注明“自由装填”的武器，意味着攻击者以一个自由动作抽出并装填弹药，实际上是使用该武器进行攻击动作的一部分 注明“次要装填”的武器，通常需要一个次要动作抽出并装填弹药。如果一个威能允许单一动作攻击多个目标，则多个投射物的装填时间是包括在使用此威能的动作中的。",
  "骑乘": "骑乘武器在你骑乘坐骑使用它时是最有效的。当你在非骑乘状态下使用骑乘武器时，你在通过它进行的攻击骰上受到-2减值。当你骑乘时，你通过骑乘武器进行的冲锋攻击造成1[W]额外伤害",
  "副手": "副手武器足够轻巧，攻击者可以在主手拿着一把武器的同时，副手拿着副手武器并使用它有效地攻击。冒险者在同一回合内不能以两把武器攻击，除非他有允许这样攻击的威能，但能够以任意一把武器来攻击",
  "触及": "通过触及武器，生物能够对离它2格的敌人以及邻近它的敌人进行近战攻击。即使如此，持用者也只能对邻近的敌人进行借机攻击，也只能夹击邻近的敌人",
  "小型": "这个特性描述的是让小型角色可以像中型角色一样使用的双手或多用武器。例如，半身人能够使用短弓，即使半身人通常不能持用双手武器",
  "厚重": "有厚重特性的武器能被视为双手武器",
  "多用": "多用武器是单手武器，但生物能以双手使用它们。这样做，攻击者会在此武器的伤害骰上获得+1加值 小型生物，例如半身人，必须以双手使用多用武器，且不在伤害骰上获得此加值",
  "自由装填": "发射投射物的远程武器，包括弓，弩，投石索，需要时间来装填。任何具有装填特性的武器都必须用双手装填，哪怕它只需要单手就能使用它攻击（例如，投石索是一种单手武器，但你需要空出另一只手来装填）。 注明“自由装填”的武器，意味着攻击者以一个自由动作抽出并装填弹药，实际上是使用该武器进行攻击动作的一部分 注明“次要装填”的武器，通常需要一个次要动作抽出并装填弹药。如果一个威能允许单一动作攻击多个目标，则多个投射物的装填时间是包括在使用此威能的动作中的。",
  "次要装填": "发射投射物的远程武器，包括弓，弩，投石索，需要时间来装填。任何具有装填特性的武器都必须用双手装填，哪怕它只需要单手就能使用它攻击（例如，投石索是一种单手武器，但你需要空出另一只手来装填）。 注明“自由装填”的武器，意味着攻击者以一个自由动作抽出并装填弹药，实际上是使用该武器进行攻击动作的一部分 注明“次要装填”的武器，通常需要一个次要动作抽出并装填弹药。如果一个威能允许单一动作攻击多个目标，则多个投射物的装填时间是包括在使用此威能的动作中的。",
};
